version: 2

sources:
  - name: github
    schema: public
    tables:
      - name: pulls
        identifier: raw_github_pulls 
        description: |
          Raw data for GitHub pull requests extracted from the GitHub API and loaded by Airflow.
        columns:
          - name: repo_name
          - name: pr_id
            description: Unique ID of the Pull Request, used as the primary key.
            tests:
              - unique
              - not_null
          - name: state
          - name: created_at
          - name: merged_at
          - name: user_login
      - name: contributions
        identifier: raw_github_contributions 
        description: |
          Raw data for GitHub Contributions extracted from the GitHub UI API and loaded by Airflow.
        columns:
          - name: username
          - name: date
          - name: contribution_count